# Copyright (C) 2019-2024 Serghei Iakovlev <egrep@protonmail.ch>
#
# This file is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file.  If not, see <https://www.gnu.org/licenses/>.

name: build

on:
  push:
    branches-ignore:
      # These should always correspond to pull requests, so ignore them for
      # the push trigger and let them be triggered by the pull_request
      # trigger, avoiding running the workflow twice.  This is a minor
      # optimization so there's no need to ensure this is comprehensive.
      - 'dependabot/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        emacs_version:
          - '29.1'
          - '29.2'
          - '29.3'
          - '29.4'
          - snapshot
        include:
          - emacs_version: snapshot
            allow_failure: true

    steps:
      - name: Setup Prerequisites
        run: |
          sudo snap install ripgrep --classic

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup GNU Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Prepare home dir
        run: ln -sf $GITHUB_WORKSPACE /home/runner/.emacs.d

      - name: Install packages
        run: make install

      - name: Check for style errors
        run: make checkdoc

      - name: Check the total line count
        run: make linescount

      - name: Byte compile configuration files
        if: matrix.allow_failure != true
        run: make build
        env:
          DEBUG: 1

      - name: Byte compile configuration files (allow failure)
        if: matrix.allow_failure == true
        run: make build || true
        env:
          DEBUG: 1
